name: Tutorials
  
on:
  push:
  pull_request:
  schedule:
    - cron:  '* */23 * * *'

env:
  REPO_NAME: 'tutorials'
  DOCKER_WORKING_DIR: '/home/dafoamuser/$REPO_NAME'
  DOCKER_MOUNT_DIR: '/home/dafoamuser/mount/$REPO_NAME'
  DOCKER_TAG: 'latest'

jobs:

  regresstion_tests:
    runs-on: ubuntu-18.04
    name: API tests
    strategy:
      fail-fast: false
      matrix:
        testConfig: [incompressible, compressible, solid]
        include:
          - testConfig: incompressible
            args: 'incompressible'
          - testConfig: compressible
            args: 'compressible'
          - testConfig: solid
            args: 'solid'
    steps:
    - uses: actions/checkout@v2
    - name: Create the docker container and run the tests
      run: |
        docker pull dafoam/opt-packages:${{env.DOCKER_TAG}}
        docker run -i -d -u dafoamuser --name regtest -v $GITHUB_WORKSPACE:${{env.DOCKER_MOUNT_DIR}} dafoam/opt-packages:${{env.DOCKER_TAG}} /bin/bash
        docker exec -i regtest /bin/bash -c "rm -rf ${{ env.DOCKER_WORKING_DIR}} && cp -r ${{env.DOCKER_MOUNT_DIR}} ${{env.DOCKER_WORKING_DIR}}"
        docker exec -i regtest /bin/bash -c ". /home/dafoamuser/loadDAFoam.sh && cd ${{env.DOCKER_WORKING_DIR}} && wget https://github.com/mdolab/dafoam/archive/master.tar.gz && tar -xvf master.tar.gz"
        docker exec -i regtest /bin/bash -c ". /home/dafoamuser/loadDAFoam.sh && cd ${{env.DOCKER_WORKING_DIR}}/dafoam-master && ./Allmake ${{matrix.args}}"
        if [ "${{matrix.args}}" = "solid" ]; then
           echo "Skip building the AD version for solid"
        else
           docker exec -i regtest /bin/bash -c ". /home/dafoamuser/loadDAFoam.sh && . /home/dafoamuser/OpenFOAM/OpenFOAM-v1812-AD/etc/bashrc && cd ${{env.DOCKER_WORKING_DIR}}/dafoam-master && ./Allclean && ./Allmake ${{matrix.args}} 2> makeWarnings.txt"
        fi
        docker exec -i regtest /bin/bash -c ". /home/dafoamuser/loadDAFoam.sh && cd ${{env.DOCKER_WORKING_DIR}}/dafoam-master && pip install ."
        docker exec -i regtest /bin/bash -c ". /home/dafoamuser/loadDAFoam.sh && cd ${{env.DOCKER_WORKING_DIR}} && ./.runTests.sh ${{matrix.args}}"
